name: RexSYS
main: space.rexum.rexsys.RexSYS
version: 1.0
author: rexjohannes98
api-version: 1.13
commands:
  kick:
  clearchat:
  rex:
  fly:
  top:
  tp:
  heal:
  feed:
  gm:
  msg:
  rtp:
  